public class Hesapla {
public static integer a=25;
public static String Name='Azra'; 
    public static integer MaxBul(integer x, integer y, integer z){
        if (x>y){
           return x; 
        }if(y>z) {
            return y;
        }else{
            return z;
        }
    }
    
    public static integer Topla(integer a, integer b){
        return a+b;
    }
    
    public static String isim(String d){
        return 'Hello '+d;
        
    }
    
    
}